title: rpass
email: rjh@sixdemonbag.org
description: >- # this means to ignore newlines until "baseurl:"
  rpass is a drop-in replacement for Ted Ts’o’s pwgen utility. Written in Rust,
  it offers strong guarantees of randomness, memory safety, and resistance to
  memory forensics.
# baseurl: "rpass" # the subpath of your site, e.g. /blog
# url: "https://rjhansen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rjhansen

# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
